config/routes.rb
Blog::Application.routes.draw do

	# namespace :seccion_articles do
	# resources :articles do
	# 	resources :comments
	# end
	# end

	resources :articles do
		resources :comments
	end


	# namespace :wellcome do
		# resources :about
	# end

	root to: 'welcome#index'

	get 'about'   => 'welcome#about',  as: :welcome_about
	get 'contact' => 'welcome#contact', as: :welcome_contact


end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	# http_basic_authenticate_with name: 'dhh', password: 'secret', except: [ :index, :show ]
	 http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

	def new
		@article = Article.new
	end


	def create

		# render plain: params[:article].inspect

		@article = Article.new(article_params_allow_inheritance_class)

		# @article.save
		# redirect_to @article

		if @article.save
			redirect_to @article
		else
			render 'new'
		end

	end


	def edit

		@article = Article.find(params[:id])

	end


	def update

		@article = Article.find(params[:id])

		if @article.update(article_params)
			# redirect_to @article
			redirect_to root_path
		else
			render 'edit'
		end

	end


	def show

		@article = Article.find(params[:id])

	end

	def destroy

		@article = Article.find(params[:id])
		@article.destroy

		redirect_to root_path

	end

	#methods private and protected
	private
	def article_params_allow_class
		params.require(:article).permit(:title, :text)
	end

	protected
	def article_params_allow_inheritance_class
		params.require(:article).permit(:title, :text)
	end

	private
	def article_params
		params.require(:article).permit(:title, :text)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create

		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)

	end

	def destroy

		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy

		redirect_to article_path(@article)

	end

	private
	def comment_params
		params.require(:comment).permit(:commenter, :body)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		@articles = Article.all
	end

	def about
	end

	def contact
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>


<% if @article.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@article.errors.count, "error") %> prohibido  guardar:</h2>
	<ul>
		<% @article.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
<p>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
</p>

<p>
	<%= f.label :text %><br>
	<%= f.text_area :text %>
</p>

<p>

	<%= button_tag(type: 'submit', class: 'btn btn-default btn-xs') do %>
	<i class="icon-ok icon-white"></i> <small> Guardar </small>
	<% end %>

</p>

<% end %>

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
<% if @article.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@article.errors.count, "error") %> prohibido  guardar:</h2>
	<ul>
		<% @article.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
<p>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
</p>

<p>
	<%= f.label :text %><br>
	<%= f.text_area :text %>
</p>

<p>

<%= button_tag(type: 'submit', class: 'btn btn-default btn-xs') do %>
 <i class="icon-ok icon-white"></i> <small> Guardar </small>
<% end %>

</p>

<% end %>

app/views/articles/show.html.erb
<table table table-striped table-hover>

	<caption> Título: <%= @article.title %> </caption>

	<tr>
		<th> Título: </th>
		<td>
			<small> <%= @article.title %> </small>
		</td>
	</tr>

	<tr>
		<th> Texto: </th>
		<td>
			<small> <%= @article.text %> </small>
		</td>
	</tr>

	<tr>
		<th> Creado el:  &nbsp;</th>
		<td>
			<small> <%= @article.created_at.strftime('%Y-%m-%d %H:%M:%S') %> </small>
		</td>
	</tr>

	<tr>
		<th> Actualizado el: &nbsp;</th>
		<td>
			<small> <%= @article.updated_at.strftime('%Y-%m-%d %H:%M:%S') %> </small>
		</td>
	</tr>

</table>


<h4>Comentarios</h4>
<% @article.comments.each do |comment| %>
<p>
	<strong>Título:</strong>
	<%= comment.commenter %>
</p>

<p>
	<strong>Comentario:</strong>
	<%= comment.body %>
</p>


<%= link_to [comment.article, comment], :class => 'btn btn-danger btn-xs' ,method: :delete, data: { confirm: 'Desea Eliminar?' } do %>
	<strong> Eliminar  </strong>
<% end %>

<% end %>

<h4>Agregar un comentario:</h4>

<%= form_for([@article, @article.comments.build]) do |f| %>
<p>
	<%= f.label :título %><br>
	<%= f.text_field :commenter %>
</p>
<p>
	<%= f.label :comentario %><br>
	<%= f.text_area :body %>
</p>
<p>
	<%= button_tag(type: 'submit', class: 'btn btn-default btn-xs') do %>
	<i class="icon-ok icon-white"></i> <strong> Guardar </strong>
	<% end %>
</p>
<% end %>


<%= link_to new_article_path, :class => 'btn btn-default btn-xs' do %>
<strong> Nuevo Articulo </strong>
<% end %>


<%= link_to edit_article_path(@article), :class => 'btn btn-warning btn-xs' do %>
<strong> Editar </strong>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Blog</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<%= render 'shared/navbar' %>

	<div class="container main-content">
		<%= yield %>
	</div>

</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">
				<%= image_tag("ruby.png", :alt => "rss feed", :style => 'width: 40px; position: absolute; left: 60px; top: 6px;') %>
				Ruby on Rails
			</a>
		</div>
		<div id="navbar" class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="">
					<%= link_to 'Inicio', root_path, method: :get %>
				</li>
				<li>
					<%= link_to 'Acerca de', welcome_about_path, method: :get %>
				</li>
				<li>
					<%= link_to 'Contacto', welcome_contact_path, method: :get %>
				</li>
			</ul>
		</div><!-- /.nav-collapse -->
	</div><!-- /.container -->
</nav>

app/views/welcome/about.html.erb
Acerda de

app/views/welcome/contact.html.erb
Contactos

app/views/welcome/index.html.erb
<table class="table table-striped table-hover">
	<caption>Lista de artículos</caption>
	<tr>
		<th class="text-muted">
			<small> Título </small>
		</th>
		<th class="text-muted">
			<small> Texto </small>
		</th>
		<th class="text-muted">
			<small> Fecha Creación </small>
		</th>
		<th class="text-muted">
			<small> Fecha Actualización </small>
		</th>
		<th class="text-muted">
			<small> Opciones </small>
		</th>
	</tr>
	<% @articles.each do |article| %>
	<tr>
		<td>
			<small><%= article.title  %></small>
		</td>
		<td>
			<small><%= article.text  %></small>
		</td>
		<td>
			<small><%= article.created_at.strftime('%Y-%m-%d %H:%M:%S') %></small>
		</td>
		<td>
			<small><%= article.updated_at.strftime('%Y-%m-%d %H:%M:%S') %></small>
		</td>
		<td>
			<%= link_to  article_path(article), :class => 'btn btn-default btn-xs' do %>
			<small>
				<strong> Mostrar </strong>
			</small>
			<% end %>

			<%= link_to edit_article_path(article), :class => 'btn btn-warning btn-xs' do %>
			<small>
				<strong> Editar </strong>
			</small>
			<% end %>

			<%= link_to article_path(article), :class => 'btn btn-danger btn-xs', method: :delete, data: { confirm: '¿Estás seguro?' }  do %>
			<small>
				<strong> Eliminar </strong>
			</small>
			<% end %>
		</td>
	</tr>
	<% end %>
</table>
<%= link_to new_article_path, :class => 'btn btn-default btn-xs' do %>
<small>
	<strong> Nuevo Articulo </strong>
</small>
<% end %>